controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login
    methods: ['POST']

api_login_check:
    path: /api/login_check

app_club:
    resource: ../src/Controller/ClubController.php
    type: annotation

rounds:
    path: /api/rounds

parcours:
    path: /api/parcourss


dev:
    path: /api/dev
    methods: ['GET']
    
